spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baiyujie111/taipingconfig.git   #github地址
          username: byj1575116@163.com      # 用户名
          password: byj15751160802      # 密码
  rabbitmq:
    host: 192.168.1.10
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/